= cmake_generator Documentation
:sectnums:
:toc: left
:toclevels: 4
:encoding: utf-8
:lang: en
:numbered:
:source-language: python
:imagesdir:   doc

== Introduction


=== How to install
This package is a simple Python module, and all default commands
works, such as:
[source,bash]
----
python setup.py install
python setup.py develop
pip install -e .
----

=== How to use

. First import the package:
+
[source, python]
----
import cmake_generator
----

== Tools

[[init_log]]
=== init_log

[source, python]
----
cmake_generator.init_log(log="cmake_generator.log", stdout_loglevel="INFO", file_loglevel="DEBUG")
----

.parameters:
* `log`: filename where to store logs. By default "cmake_generator.log"
* `stdout_loglevel`: log level for standard output (ERROR, WARNING, INFO, DEBUG)
* `file_loglevel`: log level for log file (ERROR, WARNING, INFO, DEBUG)
* [optional] `extra_config`: Set of extra properties to be added to the dict_config for logging

== pycmake.txt
The base file start with this mandatory line:
[source]
----
project JSONUtils 1.0.0 CXX
----
respectively project name, version and language used.

=== Install
If you want to install your targets use:
[source]
----
install
----
In case you want a custom installation, use:
[source]
----
install $ENV{HOME}/install
----

=== library
To add a library, do:
[source]
----
library toto_shared
    PRIVATE
        toto_shared.cpp
        sub-lib/lib.cpp
    PUBLIC
        toto_shared.h
        sub-lib/lib.h
    PUBLIC DEPENDENCY

    PRIVATE DEPENDENCY

----
Public headers will automatically be installed.

=== executable
To add an executable, do:
[source]
----
executable main.cpp
    PUBLIC DEPENDENCY
        library
    PRIVATE DEPENDENCY

----

=== TODO
Add cmake verbatim that should look like this:
[source]
----
#pycmake:cmake.begin

#pycmake:cmake.end
----

Problem is, I can't put the verbatim were it was comparatively to the original pycmake.txt file, because pycmake instructions are not executed on the fly, but rather stored and run at the end of the parsing (because the project, especially the install, need to know all the targets)