#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Main entry point to run PyCMake

@author: Christophe Cossou
"""
import sys

import cmake_generator

if __name__ == '__main__':
    try:
        cmake_generator.cmd.pycmake_from_cmdline(sys.argv[1:])
    except Exception as e:
        import traceback
        traceback.print_exc()
        sys.exit(1)
